- name: Install apt package requirements
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - gpg-agent
    - curl
    - procps
    - net-tools
    - gnupg
